### ISSUE TITLE
Discuss potential RethinkDB talk

### ISSUE THREAD

**Issue by dlindahl** [sacjs/admin#2]
Not sure if we all got this email or not, but I got the following from Christina with RethinkDB:

> Hey Derek, Andy, and Sam --
> 
> I run community at RethinkDB (www.rethinkdb.com), an open-source database that helps developers build realtime apps. We've done a lot of work with JS and our engineers would love an opportunity to give a talk about our work at the Sac JS meetup.
> 
> Here are some talks we've done before:
> - What's new with RethinkDB in 2015 (Heavybit SF Meetup) -- http://youtu.be/GuDP6hyxcng
> - Query languages and DSLs in Ruby (Silicon Valley Ruby Meetup) -- http://rethinkdb.com/videos/query-languages-and-dsls-in-ruby/
> - RethinkDB tech talk at Walmart Labs -- http://rethinkdb.com/videos/walmart-labs/
> - RethinkDB: Why Start a New Database Company (O'Reilly MySQL Conference Keynote) -- https://www.youtube.com/watch?v=uDHc3lkr3Ns
> 
> We're very much excited by open-source technologies, so our talks tend to resonate really well at local developer meetups. Let me know what your schedule looks like in the coming months -- I'd love an opportunity to set something up.
> - Christina

I responded that my initial thoughts were that since we are just getting started, we don't really know our audience and the topic of an alternative DB might be a bit advanced for us.

I floated the idea of maybe bringing in their engineers to talk about something non-RethinkDB related or pairing with a company they respect and co-presenting on a range of topics.

Does anyone on @sacjs/staff have anything to add? Is a topic like this too advanced or do you think people would show up for something like this?

**Comment by samt** [comment]
I did not get the email (maybe we should set up a list)

Probably too advanced for us right now - as you pointed out, we're still getting started. I wouldn't mind keeping the door open and having her check back at a later date. On the flip side, if they have their own outreach/marketing, it could benefit us by helping us gain local and area traction, however, I would want to make sure we have our own identity first before bringing in specific/advanced topics.
