### ISSUE TITLE
February meetup location

### ISSUE THREAD

**Issue by dlindahl** [sacjs/admin#4]
@a-axton Whats the status on using the Hive for our meetup in February and our sit down with Brandon? I'd like to start getting the ball rolling for February as early as possible.

Also, find the GitHub organization invite in your 10,999 unread emails and accept it so that I can @-mention you :smile:

**Comment by a-axton** [comment]
Sent an email to brandon, suggested monday evening for a meeting and asked if he could confirm the 25th

**Comment by a-axton** [comment]
Confirmed for feb 25th at 7:00pm. Brandon is going to be out of town next week so we may have to set a meeting up for the following week

**Comment by dlindahl** [comment]
:+1: At least we have a confirmed date for the Feb meetup. 7 is a touch later than I'd like but we can work with it.

**Comment by dlindahl** [comment]
Also, I'm going to leave this issue open until the @sacjs/staff can do the sit down. For anyone out of the loop, its really just to make sure that we match his goals as to what sort of events he wants hosted in his space. We need to work out the room fee as well (I think its $50) and then coordinate that with us and any sponsor we may have.

**Comment by a-axton** [comment]
Just talked to Brandon, he says he will be around after the meetup tomorrow if we want to talk about future events/the hive. He also mentioned that next month the 18th is available but the 25th is not.

30 mins should be fine for setup, I will probably already be here anyways and can start the setup beforehand. We'll just have to move some stuff out of the center area and bring in some chairs (there's rolling chairs, orange camping chairs or metal fold up chairs). Projector is pretty easy to get going, I think theres a thunderbolt adapter connected but not sure and also a small speaker system. The space is probably small enough so I don't think we'll need a mic.
