### ISSUE TITLE
Sponsorships

### ISSUE THREAD

**Issue by dlindahl** [sacjs/admin#6]
I talked with our arch nemesis @norfolkjs (long story :stuck_out_tongue:)  about how they handle sponsorship, specifically related to food:

> dlindahl [6:44 PM] 
> who pays for your food?
> 
> lynnaloo [6:46 PM] 
> I rotate sponsors around to pay for food directly and we have two companies that mail us sponsorship checks in case I need extra.
> 
> dlindahl [6:47 PM] 
> that sounds like work
> 
> lynnaloo [6:48 PM] 
> We just reached a size where the only venues that can fit us also cost something, but that's still usually $50 or less.
> 
> dlindahl [6:48 PM] 
> how many people do you have?
> 
> lynnaloo [6:48 PM] 
> Yep, that's usually my job. Travis does all of the "accounting" stuff and the other organizers just do what they want and put it on their resume or whatever. lol
> 
> lynnaloo [6:49 PM]
> We're averaging about 40 people now per meet-up.
> 
> dlindahl [6:49 PM] 
> was it hard to get sponsors?
> 
> dlindahl [6:50 PM]
> we went from 15 to 35 :astonished:
> 
> lynnaloo [6:51 PM] 
> It was in the beginning because I'd get companies to agree and they'd flake out or not pay us. Now we have enough members that if I can't get a cool company to sponsor then I can get one of the recruiting companies to sponsor.
> 
> lynnaloo [6:52 PM]
> We don't pay for Beer.js so that gives me a break every few months from having to figure out who's paying for stuff.
> 
> dlindahl [6:52 PM] 
> do you shoot for local companies or is anyone fair game?
> 
> lynnaloo [6:54 PM] 
> It's fair game, but the local companies are easier since they all want to hire local devs.
> 
> dlindahl [6:54 PM] 
> how much do you charge? or do they just give you :moneybag:
> 
> lynnaloo [6:56 PM] 
> I usually have them pay the catering company directly if I can.
> 
> dlindahl [6:56 PM] 
> _catering company_?
> 
> dlindahl [6:56 PM]
> you’re a baller
> 
> dlindahl [6:56 PM]
> how much does the catering usually cost?
> 
> lynnaloo [6:56 PM] 
> The re-occuring $$ just goes through Travis's consultancy if possible
> 
> lynnaloo [6:58 PM]
> So if we use the Museum of Art or the new library, we have to use their catering and that runs ~$400 (I'm not happy about that). If we can do it anywhere else, then I can have the sponsors do a Chipotle burrito bar for < $300.
> 
> dlindahl [6:58 PM] 
> ah, thats a good option. everyone loves chipotle
> 
> lynnaloo [6:59 PM] 
> Nearly all of the meetups do Pizza so people think we're highly creative to do burritos. If we do caterers, they do a bunch of finger foods,

I sent out a notice to the Meetup group to elicit sponsors to cover food, etc. I already got a response from TEKsystems, a technical recruiting company here in Sacramento offering to provide food.

Initially, they are OK with bringing sandwiches, but I'm going to try and see if we can get hot food. I think that would make for a greater impact and provide a great experience for attendees.

@sacjs/staff Does anyone have any objection to moving forward with this? Its short notice so I'd probably have to get the ball rolling ASAP.

@a-axton Do you know if Brandon would have any problem with us setting up hot food at The Hive? I wouldn't imagine it would be a problem, but I want to check in case there is.

**Comment by samt** [comment]
TEKsystems is good, just let them know before what our terms are (i.e. you get 5 minutes to talk in front of the group then people can approach you). They often provide food and will usually do sandwiches for meetups.

**Comment by dlindahl** [comment]
Haha I'm literally writing that exact thing right now :) I was going to go with 2-minutes in exchange for Chipotle. Sound reasonable?

**Comment by samt** [comment]
Sounds good :+1:

**Comment by dlindahl** [comment]
I'm using [this CascadiaJS talk as a guide](https://youtu.be/3ME7Q2YwzR0?t=20m50s)

**Comment by dlindahl** [comment]
Here is my reply:

> Thank you for your quick reply! To ensure a good relationship between the two of us, we do have a few questions for you.
> 
> As a user group, we would like to have sponsors to cover things like food and sometimes travel reimbursement for out-of-town speakers (we already have a speaker wanting to travel up from LA!). We also want to want to keep things fresh, so we fully intend to rotate sponsors, when possible.
> 
> As a sponsor, what are you looking to get out of a sponsorship arrangement?
> 
> We have no problem adding your logo to our meetup page or our pre/post-talk slides accompanied by a quick shout out during our meetup. We can also send out tweets from our Twitter account. Depending on your budget, we’d also be OK with providing you 2 minutes of speaking time after our main speakers. We just want to make sure that things don’t get too “pitchy”.
> 
> To be brutally honest with you, sometimes having recruiters at technical meetups can create a bit of friction with attendees, but that doesn’t mean it can’t work out. So given that you are a recruiting company, we want to make sure we move forward in the right direction, to benefit both TEKSystems as well as the goals of our group and our attendees. We want to make sure that our attendees view your recruiters as part of our community. Please come and listen to our speakers, learn alongside our attendees, and engage in meaningful conversations. Engaging at such an equal playing field can benefit everyone from learning about potential candidates to learning about new opportunities, but at a natural pace and in a neutral environment.
> 
> Most people come to learn amongst their peers, not get a hard sell to join a company. Having said that, if our attendees approach you with questions, by all means, go for it. Otherwise, we hope that not only can you benefit from exposure to our attendees, but hopefully your recruiters can learn more about the Javascript community as well as the greater Sacramento developer community. We’ve heard from other community organizers that the best way to recruit developers is to become part of the community and to learn and grow with them.
> 
> We pride SacJS on being more than just an ordinary local user group and as such, we’d like to stand apart from what we offer at our meetups. Do you have a particular budget in mind? While we definitely appreciate the offer of sandwiches, we think providing a hot meal, like a Chipotle burrito bar, would make for a much greater impact. We’ve heard from our sister group, NorfolkJS, that they can get Chipotle for their meetups with a budget of <$300. Is something like that doable?
> 
> Looking forward to hearing back, and thanks again for the quick reply. We are just getting started here in Sacramento and we’re excited to continue making an impact!
> 
> Derek & the SacJS Team

**Comment by dlindahl** [comment]
Here was Chelsea's reply:

> Hello Derek,
> 
> Thank you for sharing some of your hesitations and concerns with staffing companies. Let me ease some of your concerns. I am there to give insight into the local market and learn from the speakers and topics that are presented. That’s it.   I am not there to “pitch” or sell anything but rather offer knowledge of some of the technologies that I am seeing on the forefront and trends that I am seeing.
> 
> Given the opportunity, I would just like to introduce myself to the group and some of the trends that I am seeing out there currently (emphasis on responsive web design, heavy JavaScript, and Angular.JS currently).
> 
> My budget for meetups is about $100. How many people are planning on attending the meet up tomorrow night? I could do some cold appetizers or a chip and salsa bar?
> 
> Let me know your thoughts!
> 
> Chelsea

We've decided to go forward with something like sandwiches or Hot Italian, etc. Since its our first go-round, I've left it up to them. I'll add a speaking slot to the agenda.
