### ISSUE TITLE
Rocket Department Sponsorship

### ISSUE THREAD

**Issue by dlindahl** [sacjs/admin#7]
@efletch would like to become an official sponsor. If TEKSystems is covering the food, maybe we can have Rocket Dept. cover beverage costs. @samt, how much have you been spending on :beers: each month?

@efletch What is your budget and what would you like out of the sponsorship?

**Comment by efletch** [comment]
$40 - $50, @a-axton has a Rocket Dept card and can purchase on our behalf. Or we can go old school and I can write you a check. 

In return a friendly shout out would be great :) and if you have a sponsorship slide you can add our logo, but you don't need to make one specially for us

**Comment by samt** [comment]
I'll drag @a-axton to the store with me to pick up some water, beer, and ice. I don't anticipate it being over $30, still have some beer from last time!
